### ISSUE TITLE
Literature about nonlinear audio processing (distortion and amp modeling)

### ISSUE THREAD

**Issue by RinoReyns** [andrepxx/go-dsp-guitar#1]
Hi,

First of all, great work !!! All the stuff that you did is pretty impressive!!! For quite some time I have in my mind pretty similary thing that you did but I want to run all the algorithems in real-time with dedicated, custom HW. However, first I want to write more algorythms by myself for learning and better undestanding. I know how to do all the stuff with FFT, filters, delay-based effect, tremolo, wah-wah e.g. but I have some problem because I don't know how to write decent distortion or even how to start with amp modeling. Of course I can make reverse engineering of your code but I would rather prefer to read some articles/books to undestand this problem better. Can you recommend me some literature or whatever that you based on your work? Or maybe give me some different tips how to start.  

Thank you in advance,
Rino Reyns

**Comment by andrepxx** [comment]
Hi.

Thanks a lot for your appreciation! :-)

These algorithms also run in real-time. (At least "normally". You can also process WAV files. The software has two different modes, but running in real-time is the default.) I also plan to deploy this on custom hardware in the end, which should give it quite some performance boost, but it's still a bit of a way to go.

Regarding your question ...

The basic structure of an amplifier is normally pre-amplifier --> tone stack --> power amplifier, so let's take a quick look at how to model each of these.

1. Pre-amplifier

The pre-amplifier is mostly modeled using a rather simple waveshaper, that is, it takes each input sample, multiplies it by a certain factor (adjusted via "gain" value) and then maps it through a non-linear function. Popular functions are piecewise linear for hard clipping (distortion) and sigmoid functions, like area tangent hyperbolicus or logistic functions for soft clipping (overdrive). The distorted and the undistorted signal are blended together with different weights using the "drive" value. The sum of these weights is one.

For asymmetric distortion (fuzz), you add a bias voltage to the input signal before clipping it. A constant bias does not work well, since the signal will clean up (or even mute) if it drops below the bias voltage. Therefore, the best way is to derive the bias voltage from the input signal itself by rectifying (take the absolute value of the samples) and then low-pass filtering it. Add this to the input signal to achieve "DC" bias, then pass it through the non-linear function / waveshaper. You will also need a high-pass filter with a very low limit frequency after the non-linear amplifier stage to remove the DC bias again so that it does not get passed on to components further down the circuit.

The upside of using a waveshaper is, that it is fast. The downside of using a waveshaper is, that these produce an infinite amount of harmonics, which will decay exponentially towards the higher frequencies, but there will still be in principle an infinite amount of harmonics, even above the Nyquist limit, which will alias into the audio band and produce artifacts. These will be low in amplitude and therefore hard to hear in a distorted sound rich in harmonics, but in principle they are there.

You can use oversampling to increase the amount of "frequency headroom" that you have until you hit the Nyquist limit, thereby reducing aliasing. Oversampling works by using an interpolation scheme (we use the Lanczos interpolation scheme, which is a bandlimited interpolation scheme, which means that the interpolation preserves the frequency spectrum of the input signal, something that, for example, linear interpolation or spline interpolation schemes don't do) to calculate additional samples, then applying the waveshaper to the upsampled signal, applying a very steep low-pass filter to the result to remove all frequency content above the Nyquist limit and then decimating (downsampling) the signal again.

2. Tone stack

This is made of four second-order bandpass filters with different limit frequencies to decompose the signal into four bands, which are then multiplied by different factors and summed up again.

3. Power amplifier

The power amplifier has a great influence on the signal's frequency (and phase) response. To apply a frequency / phase response to a signal, one convolves the signal with an impulse response. This makes use of the fact that convolution in the time domain is multiplication in the frequency domain, so it basically applies a Fourier transform to the input signal, multiplies the result with the Fourier transform of the impulse response and performs an inverse Fourier transform afterwards. The complication is that convolution via FFT is circular convolution, but what you need for audio processing is linear convolution. To achieve this, you need a scheme for what is called "segmented convolution" or also "fast convolution" (in analogy to the "fast Fourier transform"). Such schemes are overlap-add (OLA), overlap-save or variants of those.

Of course, these short explanations don't cover a lot of ground. I just hope that they give you enough key words so that you can start your own research. Honestly, the distortion itself is not that hard. The stuff that comes after it is what makes most of the sound and that's normally filters. You can also put a filter before the "distortion unit". For example, you can put a high-pass filter before it if your input signal has too much low-frequency content and gets too "muddy" when distorted. In fact, you can also do it in go-dsp-guitar. Just put a "bandpass" unit before a distortion unit, tinker around with the lower limit frequency and the filter order and keep the higher limit frequency at 20 kHz in order not to lose highs. Since go-dsp-guitar allows for this flexibility, the "normal" pre-amplifier / distortion units do not apply this filtering by themselves.

Many algorithms in go-dsp-guitar were derived by thinking about how one would implement the corresponding signal processing in the analog domain. If you think about it this way, you will often end up with a series of simple elements interacting, for example (low-order) filters, rectifiers, oscillators, etc. For many simple systems, there are differential equations available, which model their behaviour. You can often take these differential equations and discretize them, turning them into difference equations, and then derive an algorithm from these which can be applied to the individual samples in a signal. Look for "forward Euler integration" and "initial value problem" to find out about the most relevant mathematical concepts.

Concerning literature, I actually did not buy books about signal processing or such. In fact, a lot of literature is available for free online, often not so much in the form of textbooks on an entire subject, but rather in the form of scientific literature (research papers) focusing on individual areas. If you read through enough of these and connect the ideas, you might come up with some useful algorithms. I can't tell you exactly where I picked this all up. I studied computer science and physics and I'm generally interested in audio engineering, electronics and computer simulations, so there are lots of potential sources I could pick ideas from. At some point, I started connecting all this and go-dsp-guitar is basically one of the results. Of course, if you want your models to have "realistic" sound / behaviour, you will have to take into account lots of subtleties, like how to adapt to varying time discretizations (sample rates) without changing the model's behaviour, etc.

One of the textbook sources I remember is "The Scientist and Engineer's Guide to Digital Signal Processing" from Steven W. Smith, Ph. D. It is available for free if you don't mind downloading 34 individual PDF files, but you can also find it on bookstores if you'd rather like to have it in a physical book that you can put aside your computer, or if you want to financially support the author. (And no, I don't know him personally and I don't get any share. ;-) )

In the end, the hard work is tinkering around, tuning, testing, measuring a lot, and, most important, really a ton of optimization to get it fast. Also consider testing and measuring with real, analog equipment, if you can. For example, connect a real guitar to your computer when comparing different algorithms / parametrizations to decide upon which are the ones you should use. Measure impulse responses of real amps / cabinets with good mics and so on. If you can get hold of a function generator, oscilloscope or even spectrum analyzer, these might also be helpful for performing actual measurements on analog circuits or sometimes simply for getting some intuition or inspiration.

I hope this is helpful and gets you started. Keep in mind that this is a long way though, especially if you want your models to be reasonably "exact".

Regards.

**Comment by RinoReyns** [comment]
WoW!!!! Thanks!!! I appreciate all the things you have written and it's a great starting point for me. I'm a bit speechless because of your kindness in knowledge sharing. Of course I don't expect easy work, but for me hard work makes gatter fun along the ride, especially in audio processing. Certainly, I will have to analyze and understand all that you mentioned. Nevertheless, thank you once again and I wish you luck and patience in your project development. 

Regards.

**Comment by RinoReyns** [comment]
WoW!!!! Thanks!!! I appreciate all the things you have written and it's a great starting point for me. I'm a bit speechless because of your kindness in knowledge sharing. Of course I don't expect easy work, but for me hard work makes gatter fun along the ride, especially in audio processing. Certainly, I will have to analyze and understand all that you mentioned. Nevertheless, thank you once again and I wish you luck and patience in your project development. 

Regards.
