### ISSUE TITLE
Applying effects to audio file

### ISSUE THREAD

**Issue by Edwin-Luijten** [andrepxx/go-dsp-guitar#2]
First thing first, awesome job you did here.

I was wondering, I have an audio sample from a file. Uncompressed 16-bit signed little-endian samples (Linear PCM). Audio content returned as LINEAR16 also contains a WAV header.

Is it possible to use your components to apply certain effects to the audio?

**Comment by andrepxx** [comment]
Hi Edwin-Juijten,

first note that *go-dsp-guitar* has a batch processing mode and can already apply its effects to files in either RIFF WAV or RF64 format. If you simply want to apply effects to WAV files, this is the easiest way to achieve this, so I will explain this first. However, I expect you want to do this programmatically and I will also explain that later on.

To use *go-dsp-guitar* in batch processing mode, simply invoke the `dsp` executable suitable for your target platform (e. g. `dsp-linux-amd64`) with the argument `-channels N`, replacing N with the number of channels you want to process.

The application will then ask you for a sample rate. This is in *Hertz*, so enter for example 96000 to use 96 kHz. This is the sample rate you expect the *output* to be in and it also determines the time step used by the simulation. (Remember that *go-dsp-guitar* uses a circuit simulation to simulate its effects. The time step *dt* of this simulation is the inverse of the sample rate *f* or *dt = 1 / f*.) The sample rate(s) of the input file(s) can be arbitrary and will be resampled on-the-fly to the "target sample rate" you enter here before passing the signal through the simulation. All outputs will be saved in the sample rate the simulation was run at.

After you entered the sample rate, the application will tell you "Web interface ready: " followed by a URL. You can then use the application in a way that is similar to to what you would do when you use it in real-time mode with JACK. Just open up your web browser to configure the processing. You will have one signal chain for each channel you entered when you invoked the application, so when you started this with `-channels 1` you will have one signal chain and if you started this with `-channels 8` you will have eight signal chains.

After you configured your processing chain(s) and effects units, you can click on the "Process now" button. The web interface in the browser will then "freeze". Open up the terminal where the `go-dsp-guitar` executable is running and the application will now ask you for the path to each `.wav` or `.rf64` file you want to process and, if this file contains multiple channels, from which of the channels the input shall be taken. (You can only feed a single channel into each of the processing chains.) If you want to process, say, the left and right channel of a stereo WAV file using two processing chains, simply enter the path to the same input file twice, but once enter `0` as the channel number and once enter `1` as the channel number. The outputs will always be stored in separate monophonic WAV files though. You will need to use external software, such as *Audacity*, to merge them into a stereo file again and / or to do further editing.

**Be careful with the output paths! If you supply a path to a file that already exists, it will get overwritten.** If you supply an empty output path, that particular output will be discarded.

If you simply want to process files you have on disk to apply effects to them, this will be enough. If you only have the files in an in-memory buffer want to use algorithms from *go-dsp-guitar* in your own application to process these, I will now explain you how you can do this.

**Keep in mind though that these interfaces are internal to *go-dsp-guitar* and may change at any time. *go-dsp-guitar* is an application designed for a specific purpose. It is NOT a general-purpose audio or signal processing library and should not be used as one. We therefore cannot promise that these interfaces will remain stable in any way.**

Okay. So let's say you have a buffer `buf` of type `[]byte` that contains the contents of an entire RIFF WAV / RF64 file, including the `RIFF` / `RF64` header and at least a format (`fmt` - not to be confused with the *golang* package of the same name) and a `data` chunk. You can then parse this buffer using `github.com/andrepxx/go-dsp-guitar/wave` as following.

```go
package main

import (
	"github.com/andrepxx/go-dsp-guitar/wave"
)

func main() {
	buf := []byte{}

	/*
	 * TODO: Fill this somehow, i. e. read it from a file using `io/ioutil`
	 * or create the contents programmatically.
	 */

	f, err := wave.FromBuffer(buf)
	// ...
}
```

If `buf` contained a well-formed RIFF WAVE / RF64 file (and the parser is pretty picky), then `f` will be non-`nil` and of type `wave.File` and `err` will be nil. If the contents of `buf` were not a well-formed RIFF WAVE / RF64 file, then `f` will be `nil` and `err` will be non-`nil` and of type `error` and the string returned by `err.Error()` will explain what went wrong.

If the parsing succeeded, you can query `f` for the following.

- `f.SampleFormat()`: This will return either `wave.AUDIO_PCM` if the file contains integer samples or `wave.AUDIO_IEEE_FLOAT` for floating-point samples in IEEE 754 format. The returned value is of type `uint16`.
- `f.BitDepth()`: This will either return one of {8, 16, 24, 32} if `f.SampleFormat()` returned `wave.AUDIO_PCM` or one of either {32, 64}, if `f.SampleFormat()` returned `wave.IEEE_FLOAT`. The returned value is of type `uint16`.
- `f.SampleRate()`: This will return the sample rate of the file in *Hertz*, e. g. 96000 for a 96 kHz file. The returned value is of type `uint32`.
- `f.ChannelCount()`: This will return the number of channels stored in the file, e. g. `1` for a monophonic file, `2` for a stereophonic file, and so on. The returned value is of type `uint16`.
- `f.Bytes()`: This will serialize the file into a byte representation again. Note that this representation does not have to be identical to the buffer the file was parsed from. For example, some chunks that were ignored could be removed and / or the file contents could have been changed programmatically. (A `wave.File` is not immutable.)
- `f.Channel(id uint16)`: Pass an `id`, which must be strictly lower than `f.ChannelCount()` and a non-`nil` value of type `wave.Channel` and a `nil` value of type `error` will be returned. If the `id` is out of range, a `nil` value of type `wave.Channel` and a non-`nil` value of type `error` will be returned.

For example, invoke `c, _ := f.Channel(0)` to obtain the only channel from a monophonic WAVE file.

After you obtained the `wave.Channel`, you can invoke `samples := c.Floats()` on the channel to obtain all samples as a buffer of type `[]float64`. The values will be in the range [-1; 1] if `f.SampleFormat()` returned `wave.AUDIO_PCM`. They may be outside of this range for `wave.AUDIO_IEEE_FLOAT` if the WAVE file contains such out-of-range floating-point values.

Note that this is not required. You may use any method to obtain these samples. You just have to make sure that they are of type `[]float64`, are in the range [-1; 1] and that you know the sample rate if you want to use the effects units provided by *go-dsp-guitar*, since these are the main assumptions that they make.

To apply effects to your audio, add the `github.com/andrepxx/go-dsp-guitar/effects` package to your `import` statement.

You can then use the method `effects.CreateUnit(unitType int)` to create an `effects.Unit`. If `u` is such an `effects.unit`, you can then invoke the following methods on it.

- `u.Parameters()`: This will return the parameters that this unit has. The returned value is of type `[]effects.Parameter`. I will describe below, how such an `effects.Parameter` looks like.
- `u.Type()`: Returns the unit type of this unit as an `int`. This will be one of the values defined in the `effects.UNIT_...` constants.
- `u.SetDiscreteValue(name string, value string)`: Sets the discrete parameter with the name `name` to the discrete value `value`. Returns `nil` if this was successful or a non-`nil` value of type `error` if it was not.
- `u.GetDiscreteValue(name string)`: Obtains the discrete parameter with the name `name` and returns its value as a `string`, alongside an `error` value. The `error` is `nil` if a discrete parameter with the name `name` exists or and non-`nil` if it does not.
- `u.SetNumericValue(name string, value int32)`: Sets the discrete parameter with the name `name` to the numeric value `value`. Returns `nil` if this was successful or a non-`nil` value of type `error` if it was not.
- `u.GetNumericValue(name string)`: Obtains the discrete parameter with the name `name` and returns its value as an `int32`, alongside an `error` value. The `error` is `nil` if a discrete parameter with the name `name` exists or and non-`nil` if it does not.

If `p` is an `effects.Parameter`, you can read the following fields from it.

- `p.Name`: The name of the parameter as a `string`, e. g. `"gain"`.
- `p.Type`: The type of the parameter as an `int32`. This is either `effects.PARAMETER_TYPE_NUMERIC` or `effects.PARAMETER_TYPE_DISCRETE`.
- `p.PhysicalUnit`: The physical unit of this parameter as a `string`, e. g. `"dB"`. You can expect this to be be relevant only if `p.Type == effects.PARAMETER_TYPE_NUMERIC`. It is irrelevant if `p.Type == effects.PARAMETER_TYPE_DISCRETE`.
- `p.Minimum`: The minimum value allowed for this parameter, if `p.Type == effects.PARAMETER_TYPE_NUMERIC`. It is irrelevant if `p.Type == effects.PARAMETER_TYPE_DISCRETE`. For example, this could be `-30` to indicate that *-30 dB* is the minimum gain permitted.
- `p.Maximum`: The maximum value allowed for this parameter, if `p.Type == effects.PARAMETER_TYPE_NUMERIC`. It is irrelevant if `p.Type == effects.PARAMETER_TYPE_DISCRETE`. For example, this could be `30` to indicate that *30 dB* is the maximum gain permitted.
- `p.NumericValue`: The value that this parameter is currently set to, if `p.Type == effects.PARAMETER_TYPE_NUMERIC`. It is irrelevant if `p.Type == effects.PARAMETER_TYPE_DISCRETE`. For example, this could be `5` to indicate that the gain of this `effects.Unit` is currently set to *5 dB*.
- `p.DiscreteValueIndex`: If `p.Type == effects.PARAMETER_TYPE_DISCRETE`, this contains the index into the list `p.DiscreteValues` of the discrete value that is currently selected for this parameter. It is irrelevant if `p.Type == effects.PARAMETER_TYPE_NUMERIC`.
- `p.DiscreteValues`: This is a list of type `[]string` containing the discrete values allowed for this parameter, if `p.Type == effects.PARAMETER_TYPE_DISCRETE`. This is `nil` if `p.Type == effects.PARAMETER_TYPE_NUMERIC`.

To set an `effects.Parameter` to the value `v` (of type `int32`) where `p.Type == effects.PARAMETER_TYPE_NUMERIC` on an `effects.Unit` called `u`, do the following.

```go
u.SetNumericValue(p.Name, v)
```

If everything went alright, this will return `nil`. If something went wrong, it will return a non-`nil` value of type `error`.

To set an `effects.Parameter` to the value `v` (of type `string`) where `p.Type == effects.PARAMETER_TYPE_DISCRETE` on an `effects.Unit` called `u`, where `v` is contained in `p.DiscreteValues`, do the following.

```go
u.SetDiscreteValue(p.Name, v)
```

The meaning of the return value is the same as for `u.SetNumericValue(...)`.

After you configured everything, you can invoke the following to process a buffer by that `effects.Unit`.

```go
u.Process(in, out, sampleRate)
```

Where `in` is of type `[]float64` and contains the samples to be processed, `out` is of type `[]float64` and `len(in) == len(out)` and `sampleRate` is of type `uint32`. (This may not always get checked, so your application may crash with an index out of bounds error, especially when `len(in) > len(out)`. When `len(in) < len(out)`, then `out` may contain junk at the tail. Note that none of this is defined behaviour though. An `effects.Unit` definitely expects that `len(in) == len(out)`.)

Note that each `effects.Unit` is stateful. You can break the buffer into chunks and `Process(...)` them sequentially and the result should be the same as (or pretty close to) what you'd obtain if you were to `Process(...)` the entire stream at once. If you have to reset that state because you want to start from scratch with a "new simulation", you will have to re-create the `effects.Unit`-s.

Note that instead of using individual `effects.Unit`-s from `github.com/andrepxx/go-dsp-guitar/effects`, you may also use an entire `signal.Chain` from `github.com/andrepxx/go-dsp-guitar/signal` to process your signal.

You can then `c.AppendUnit(unitType int)`, `c.RemoveUnit(id)` (where `id` is the index of the unit to be removed, counted from the beginning of the signal chain), if `c` is of type `signal.Chain`. In addition `signal.Chain` contains most of the methods that `effects.Unit` contains, just with an additional `id` parameter of type `int` at the beginning, which serves as an index to identify the unit to which the command shall be applied. You can also bypass a unit and / or re-order your `signal.Chain` by moving `effects.Unit`-s "up" (towards the front / input side of) and down (towards the back / output side of) the chain, so `signal.Chain` is a slightly higher-level abstraction than `effects.Unit`.

A `signal.Chain` also provides a `Process(...)` method with the same signature as the `Process(...)` method on an `effects.Unit`. When you invoke the `Process(...)` unit on a `signal.Chain`, it will inject the signal into the input of the first unit, pass it through the entire signal chain (each unit feeding its output into the input side of the subsequent unit) and then obtain the output from the last unit.

For example, to create an 8th-order bandpass filter with a lower limit frequency of 300 Hz and an upper limit frequency of 3 kHz as an `effects.Unit`, do the following.

```go
u := effects.CreateUnit(effects.UNIT_BANDPASS)
u.SetDiscreteValue("filter_order", "8")
u.SetNumericValue("frequency_1", 300)
u.SetNumericValue("frequency_2", 3000)
```

Another example, here we create a `signal.Chain`, which consists of a soft-clipping non-linear amplifier with a `gain` of *30 dB*, followed by an 8th-order bandpass filter with a lower limit frequency of 300 Hz and an upper limit frequency of 3 kHz.

```go
// Create signal chain
c := signal.CreateChain(nil)

// First pass signal through an overdrive unit, then through a bandpass filter
c.AppendUnit(effects.UNIT_OVERDRIVE)
c.AppendUnit(effects.UNIT_BANDPASS)

// Configure the overdrive unit (which has id 0)
c.SetNumericValue(0, "gain", 30)

// Configure the bandpass unit (which has id 1)
c.SetDiscreteValue(1, "filter_order", "8")
c.SetNumericValue(1, "frequency_1", 300)
c.SetNumericValue(1, "frequency_2", 3000)
```

We can then use `c.Process(...)` in exactly the same way we used `u.Process(...)` above.

The `signal.CreateChain(nil)` is ugly. We normally have to pass `filter.ImpulseResponses` as an argument here, which is a data structure describing amplifier impulse responses. Creating `filter.ImpulseResponses` is ugly though, since they have to be imported from a directory on the file system which contains a certain file structure consisting of RIFF WAVE files storing the actual impulse responses along with a JSON file storing both the paths to these RIFF WAVE files and additional meta-information to be used alongside each file. However, as long as we don't try to add an `effects.Unit` of type `effects.UNIT_POWERAMP`, everything will be alright if this data structure is `nil`.

Note that the value of `filter_order` is a `string` since `p.Type == effects.PARAMETER_TYPE_DISCRETE` for the corresponding `effects.Parameter`. (You can query `c` after appending the units to determine this dynamically at run-time.)

Finally, if you want to roll your own audio application, you might also find the packages `github.com/andrepxx/go-dsp-guitar/fft` (which implements an efficient Fast Fourier Transform for real- and complex-valued vectors) and `github.com/andrepxx/go-dsp-guitar/resample` (which implements bandlimited sample rate conversion using a Lanczos interpolation scheme) useful.

I hope this helps.

Regards.

**Comment by Edwin-Luijten** [comment]
Thanks for your time to explain it in this great detail, awesome.

So, based on your well written explanation I came to below working code.
My goal is to apply an autotune effect (not sure which effect i need yet but I hope to figure it out).
`
func (a *AudioProcessor) Process(audio []byte) ([]byte, error) {
        out := make([]float64, len(audio))
	f, err := wave.FromBuffer(audio)
	if err != nil {
		return nil, err
	}

	if f == nil {
		return nil, errors.New("invalid audio format")
	}

	c, err := f.Channel(0)
	if err != nil {
		return nil, err
	}

	samples := c.Floats()

	u := effects.CreateUnit(effects.UNIT_DISTORTION)
	u.SetNumericValue("boost", 15)
	u.SetNumericValue("gain", 0)
	u.SetNumericValue("level", 0)
	u.Process(samples, out, 24000)

	n, err := wave.CreateEmpty(f.SampleRate(), f.SampleFormat(), f.BitDepth(), f.ChannelCount())
	if err != nil {
		return nil, err
	}

	c, err = n.Channel(0)
	if err != nil {
		return nil, err
	}

	c.WriteFloats(out)

	return n.Bytes()
}
`

**Comment by andrepxx** [comment]
> My goal is to apply an autotune effect (not sure which effect i need yet but I hope to figure it out).

Autotune in the sense of "change the pitch of a sound to the value I want"?

There is no unit for this. You will have to implement this on your own. I have no idea how. It's quite an uncommon / exotic effect and I actually have no idea how one would do it.

Let me provide some "corrections" to your code. I will put comments on them explaining why I'd do it in this way.

```go
func (a *AudioProcessor) Process(audio []byte) ([]byte, error) {
	f, err := wave.FromBuffer(audio)

	if err != nil {
		return nil, err
	}

	// f != nil if err == nil, so no need to check again

	c, err := f.Channel(0)

	if err != nil {
		return nil, err
	}

	samples := c.Floats()

	// len(audio) is the number of BYTES in the file
	// len(samples) is the number of samples in the channel 0
	out := make([]float64, len(samples))

	// Read the sample rate from file instead of hard-coding it
	fs = f.SampleRate()

	/*
	 * Doesn't really matter if you use "boost" or "gain", but normally
	 * you'd use "gain" as long as it has range and then "boost" if that's
	 * still not enough and you want to push your signal really hard.
	 *
	 * Or you'd use "boost" if your signal level is low to bring it into
	 * normal range and then "gain" to clip it.
	 *
	 * Technically it doesn't matter. It's only separated for conceptual
	 * purpuses.
	 */
	u := effects.CreateUnit(effects.UNIT_DISTORTION)
	u.SetNumericValue("boost", 0)
	u.SetNumericValue("gain", 15)
	u.SetNumericValue("level", 0)
	u.Process(samples, out, fs)

	// You only write to one channel, so no need to create more
	n, err := wave.CreateEmpty(fs, f.SampleFormat(), f.BitDepth(), 1)

	if err != nil {
		return nil, err
	}

	c, err = n.Channel(0)

	if err != nil {
		return nil, err
	}

	c.WriteFloats(out)
	return n.Bytes(), nil
}
```

I did not try it out, but it should work.

> On thing I'm not understanding yet, is why the filterChain results into a silent audio file, it's 2.4MB but I don't hear anything.

Same code as above, just replacing the `effects.Unit` called `u` with the `signal.Chain` called `c`?

That should work. Can you open the file in a hex editor and check if the `data` segment is all zeroes?

**Comment by Edwin-Luijten** [comment]
I applied some corrections based on your comment, the result audio is not silent anymore. Tough I don't notice the effects I applied, I'm applying some random effects but the end result sounds the same as the input:

```go
	f, err := wave.FromBuffer(audio)
	if err != nil {
		return nil, err
	}

	if f == nil {
		return nil, errors.New("invalid audio format")
	}

	c, err := f.Channel(0)
	if err != nil {
		return nil, err
	}

	samples := c.Floats()
	out := make([]float64, len(samples))

	s := signal.CreateChain(nil)

	s.AppendUnit(effects.UNIT_OVERDRIVE)
	s.AppendUnit(effects.UNIT_BANDPASS)
	s.AppendUnit(effects.UNIT_DISTORTION)

	s.SetNumericValue(0, "gain", 30)
	s.SetNumericValue(0, "boost", 30)
	s.SetNumericValue(0, "drive", 100)

	s.SetDiscreteValue(1, "filter_order", "8")
	s.SetNumericValue(1, "frequency_1", 300)
	s.SetNumericValue(1, "frequency_2", 3000)

	s.SetNumericValue(2, "gain", 15)

	fmt.Println("input sample length: ", len(samples), "output sample length:", len(out))
	s.Process(samples, out, f.SampleRate())

	n, err := wave.CreateEmpty(f.SampleRate(), f.SampleFormat(), f.BitDepth(), 1)
	if err != nil {
		return nil, err
	}

	c, err = n.Channel(0)
	if err != nil {
		return nil, err
	}

	c.WriteFloats(out)
	return n.Bytes()
```

**Comment by andrepxx** [comment]
I think there's only one thing missing.

A `signal.Chain` is not really a list of `effects.Unit`-s. It is rather a list of slots. Each slot then contains an `effects.Unit`, *but* it can also be "bypassed".

A "bypassed" `effects.Unit` can be handled as any other one. It can be moved along the signal chain (*) and you can configure its parameters. However, the `Process(...)` method of an `effects.Unit` in a bypassed slot is not invoked. This is done to save processing power.

(*) In fact, not just the `effects.Unit`-s, but the entire slots are moved along the signal chains, so that the information whether a unit is bypassed or not moves along with it.

If we were to implement the "bypassing" in the `effects.Unit` itself, each bypassed unit would have to copy the contents of the input to the output buffer, since the "bypassing" would then be "internal" to the unit and the "contract" of the interface of an `effects.Unit` requires it to read all samples from its input, process them and write processed samples to the output. That's why the "bypass value" is not an `effects.Parameter`. Because we let the `signal.Chain` handle the bypassing, it becomes very cheap, since it effectively results into the `Process(...)` method of the bypassed unit not being invoked and some pointer manipulation so that the next non-bypassed unit in the chain reads directly from the output of the last unit that was actually invoked.

But the internals don't really matter so much. This is what you need to do to "un-bypass" your units.

```go
s.SetBypass(0, false)
s.SetBypass(1, false)
s.SetBypass(2, false)
```

Units are "bypassed" by default when they're added. That's because, when they're added, they're always added to the *end* of the processing chain and they have their parameters set to default values. If they were non-bypassed, adding a unit might have an undesirable effect on the sound and, when used in real-time mode in *go-dsp-guitar*, all manipulations to the signal chain will immediately affect the live signal. By adding all units in bypassed mode to the chain, we give the musician the opportunity to put it where it belongs, configure its parameters and only *then* (after everything's set up as desired) enable the effect, so we don't get "strange results" from the intermediate steps required to set the effects unit up.

A musician can also use the "bypass" feature to simply disable an effect and keep all its parameters at the values they were set to and then re-enable it later, just as he / she would do with a real stomp-box on stage.

But yeah, that's what you need to do. Set bypass to false for each unit (or, technically, slot where the unit is in) you want to be active, i. e. actually affect the signal.

**Comment by Edwin-Luijten** [comment]
Really love your detailed explaination. I learn alot from them and your code about audio processing =)

**Comment by andrepxx** [comment]
Just a few more hints.

1. When *go-dsp-guitar* does the processing, it obviously does a little bit more. In addition to the "normal" `effects.Unit`-s that the user can put into `signal.Chain`-s, there are also a few "global units" (which are technically not `effects.Unit`-s but have their own types and packages, but appear much like effects units in the UI) like the tuner, the metronome or the spatializer that process signals.

The spatializer, for example, takes the output of each `signal.Chain` and puts it into a stereo field at a certain position. It will calculate the signal level and difference in time of arrival from a signal source at the configured position and the user's ears and then manipulate the signals accordingly, even though *go-dsp-guitar* will also provide you the output signals of each signal chain before "spatialization".

The metronome is basically its own signal source / "chain". It creates a monophonic click track using impulse responses as clicks.

The tuner will get the its signal from the beginning of a `signal.Chain` (so normally directly from a hardware input), feed it through a ring buffer and allow for asynchronous analysis of the "snapshot" in the buffer to determine its fundamental frequency, note value and deviation in cents.

2. When *go-dsp-guitar* runs in batch-processing mode, it doesn't actually invoke the `Process(...)` methods of its `signal.Chain`-s on the contents of an entire `wave.Channel` at once. It rather runs over the samples taking buffers of a certain size (in *go-dsp-guitar* we use 8192 samples), invokes `Process(...)` for each of these, and finally stitches the results back together. With your code, all the samples in your wave file first run through the first effects unit, then through the second, etc. What *go-dsp-guitar* does is, it takes the first 8192 samples from the file, runs them through all the effects units, one after the other, obtains the results, then takes the next 8192 samples from the file, runs them through all the effects units, obtains the results, and so on.

3. *go-dsp-guitar* will allow you to choose the "target sample rate" the simulation will run at independently from the input. This is (partly) because we can supply multiple inputs to *go-dsp-guitar*. If these files have different sample rates, then which should we take? Therefore, we let the user choose. This also prevents us from running at "weird" sample rates in case the WAVE file was created with one. (Technically, you can create a WAVE file which was sampled at 13487 Hz, but some of the algorithms in *go-dsp-guitar* might not run at arbitrary rates. In fact, exactly the `effects.UNIT_POWERAMP` will only produce useful results at certain pre-defined sample rates.) It will also let you choose the sample format (integer or floating-point) and bit-depth for each of the output files. This does not have to be identical to the input at all. You could, for example, provide an 8 bit integer WAVE file sampled at 22.05 kHz as an input to *go-dsp-guitar*, and have it produce a 64 bit floating-point output sampled at 192 kHz. This would be perfectly valid. And especially the choice of the sample format (integer or float) and bit depth comes at very little cost, since you will always provide float buffers to the `wave` package. You just have to set the parameters differently to store it in another discretization.

Regards.

**Comment by andrepxx** [comment]
I consider this issue resolved.
