### ISSUE TITLE
Could not open config file: 'config/config.json'

### ISSUE THREAD

**Issue by Imeguras** [andrepxx/go-dsp-guitar#5]
Error on arch linux on both normal and -bin aur repository 
2020-12-31 at 03:52

**Comment by andrepxx** [comment]
We do not maintain the _Arch_ packages. Have you tried the latest Tarball from the "Releases" page of this repository?

Just extract it "somewhere", open a Terminal window, navigate to that directory using "cd", then run ...

`./dsp-linux-amd64`

You need to start _JACKd_ first before doing this.

Hope this works.

Regards.

**Comment by andrepxx** [comment]
So, just to clarify again. If you're looking for a binary release, I'd suggest that you try the topmost (non-"source") file from the following page.

https://github.com/andrepxx/go-dsp-guitar/releases/latest

Just extract that archive "somewhere" (either using `tar xvzf` on the console or with a graphical archive tool), navigate to the `go-dsp-guitar` directory that was created, then run the `dsp-...` executable that's suitable for your architecture (likely the `dsp-linux-amd64`).

The thing is that we use relative paths a lot, so the auxiliary files that we supply have to be kept in a certain location relative to the executables, and (assuming the executables are on your `$PATH`) your environment needs to have the correct "working directory" (`pwd`) set so that we load the correct files. (You can't just run the executable "from anywhere", like you can do it with system binaries like `ls`.)

I have no idea, where exactly the _Arch_ packages put (both executable and non-executable) files in the file system hierarchy and if they got all the paths correct. The message looks like there's somehow an issue with that, so I'd ask you to try with the packages that we supply, which are also more recent. (The AURs are still at `v1.6.1`.)

If the issues just appear just with the _Arch_ packages, and the releases from this *GitHub* repository work, then it's probably best to report the issue to the _AUR_ maintainer.

Regards.

**Comment by andrepxx** [comment]
So, just to clarify again. If you're looking for a binary release, I'd suggest that you try the topmost (non-"source") file from the following page.

https://github.com/andrepxx/go-dsp-guitar/releases/latest

Just extract that archive "somewhere" (either using `tar xvzf` on the console or with a graphical archive tool), navigate to the `go-dsp-guitar` directory that was created, then run the `dsp-...` executable that's suitable for your architecture (likely the `dsp-linux-amd64`).

The thing is that we use relative paths a lot, so the auxiliary files that we supply have to be kept in a certain location relative to the executables, and (assuming the executables are on your `$PATH`) your environment needs to have the correct "working directory" (`pwd`) set so that we load the correct files. (You can't just run the executable "from anywhere", like you can do it with system binaries like `ls`.)

I have no idea, where exactly the _Arch_ packages put (both executable and non-executable) files in the file system hierarchy and if they got all the paths correct. The message looks like there's somehow an issue with that, so I'd ask you to try with the packages that we supply, which are also more recent. (The AURs are still at `v1.6.1`.)

If the issues appear only with the _Arch_ packages, and the releases from this *GitHub* repository work, then it's probably best to report the issue to the _AUR_ maintainer.

Regards.

**Comment by andrepxx** [comment]
I think that this issue is resolved.

If you still encounter issues with our "official" release, feel free to open a new ticket.
